//
// File generated by HDevelop for HALCON/.NET (C#) Version 22.11.1.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;
using System.Drawing;
using TimeTech.Core.Common;

public partial class HDevelopExport
{
  public HObject ho_P1r;


    public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");

  }

  // Main procedure 
  public void actionBL(Bitmap orgPic, ref Bitmap clipPic,string clipInformation)
  {
        // Local iconic variables 
        HImage hi_Image;
    HObject ho_Image, ho_Image11, ho_Image12, ho_Image13;
    HObject ho_ImageScaled, ho_Regions, ho_RegionOpening, ho_RegionDilation;
    HObject ho_ConnectedRegions, ho_SelectedRegions, ho_RegionTrans;
    HObject /*ho_P1r, */ ho_ImageReduced;

    // Local control variables 

    HTuple hv_Area = new HTuple(), hv_Row = new HTuple();
    HTuple hv_Column = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_Image11);
    HOperatorSet.GenEmptyObj(out ho_Image12);
    HOperatorSet.GenEmptyObj(out ho_Image13);
    HOperatorSet.GenEmptyObj(out ho_ImageScaled);
    HOperatorSet.GenEmptyObj(out ho_Regions);
    HOperatorSet.GenEmptyObj(out ho_RegionOpening);
    HOperatorSet.GenEmptyObj(out ho_RegionDilation);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
    HOperatorSet.GenEmptyObj(out ho_RegionTrans);
    HOperatorSet.GenEmptyObj(out ho_P1r);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    ho_Image.Dispose();
        //HOperatorSet.ReadImage(out ho_Image, "D:/项目/钙钛矿/F117/明场/1.png");  //传图
        halconProvider.Bitmap2HObjectBpp24(orgPic, out ho_Image);  //Bitmap2HObjectBpp24 彩图 Bitmap2HObjectBpp8、Bitmap2HObjectBpp16黑白图
        //ho_Image= (HObject)hi_Image.Clone();
        //Image Acquisition 01: Do something
        ho_Image11.Dispose();ho_Image12.Dispose();ho_Image13.Dispose();
    HOperatorSet.Decompose3(ho_Image, out ho_Image11, out ho_Image12, out ho_Image13 );  //Decompose3用彩图  Decompose1，Decompose2黑白图
        ho_ImageScaled.Dispose();
    HOperatorSet.ScaleImage(ho_Image12, out ho_ImageScaled, 2, -270);
    ho_Regions.Dispose();
    HOperatorSet.Threshold(ho_ImageScaled, out ho_Regions, 0, 100);
    ho_RegionOpening.Dispose();
    HOperatorSet.OpeningRectangle1(ho_Regions, out ho_RegionOpening, 20, 20);
    ho_RegionDilation.Dispose();
    HOperatorSet.DilationRectangle1(ho_RegionOpening, out ho_RegionDilation, 20, 
        20);
    ho_ConnectedRegions.Dispose();
    HOperatorSet.Connection(ho_RegionDilation, out ho_ConnectedRegions);
    ho_SelectedRegions.Dispose();
    HOperatorSet.SelectShapeStd(ho_ConnectedRegions, out ho_SelectedRegions, "max_area", 
        5000000);
    ho_RegionTrans.Dispose();
    HOperatorSet.ShapeTrans(ho_SelectedRegions, out ho_RegionTrans, "convex");
    hv_Area.Dispose();hv_Row.Dispose();hv_Column.Dispose();
    HOperatorSet.AreaCenter(ho_RegionTrans, out hv_Area, out hv_Row, out hv_Column);
    if ((int)(new HTuple(hv_Area.TupleGreater(500))) != 0)
    {
      //加入日志,区域截取成功
    }
    ho_P1r.Dispose();
    HOperatorSet.DilationRectangle1(ho_RegionTrans, out ho_P1r, 30, 30);
    ho_ImageReduced.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_P1r, out ho_ImageReduced);
        halconProvider.HObject2Bpp24(ho_ImageReduced, out clipPic);
    //HOperatorSet.WriteObject(ho_P1r, "路径");  //保存文件
    HOperatorSet.WriteObject(ho_P1r, clipInformation);  //保存文件路径
    ho_Image.Dispose();
    ho_Image11.Dispose();
    ho_Image12.Dispose();
    ho_Image13.Dispose();
    ho_ImageScaled.Dispose();
    ho_Regions.Dispose();
    ho_RegionOpening.Dispose();
    ho_RegionDilation.Dispose();
    ho_ConnectedRegions.Dispose();
    ho_SelectedRegions.Dispose();
    ho_RegionTrans.Dispose();
    ho_P1r.Dispose();
    ho_ImageReduced.Dispose();  //扣边后的图

    hv_Area.Dispose();
    hv_Row.Dispose();
    hv_Column.Dispose();

  }




}


