//
// File generated by HDevelop for HALCON/.NET (C#) Version 22.11.1.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;
using System.Drawing;
using TimeTech.Core.Common;

public partial class HDevelopExport
{

  // Main procedure 
  public void action(Bitmap orgPic, ref Bitmap clipPic, string clipInformation)
  {


    // Local iconic variables 

    HObject ho_Image, ho_P1r, ho_ImageReduced;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_P1r);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    ho_Image.Dispose();
        //HOperatorSet.ReadImage(out ho_Image, "D:/项目/钙钛矿/F117/明场/1.png");  //传图
        halconProvider.Bitmap2HObjectBpp24(orgPic, out ho_Image);

    ho_P1r.Dispose();
        //HOperatorSet.ReadObject(out ho_P1r, "D:/项目/钙钛矿/拼图测试/F129/1_reduce.hobj");  //传位置文件
        HOperatorSet.ReadObject(out ho_P1r, clipInformation);  //传位置文件
        ho_ImageReduced.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_P1r, out ho_ImageReduced);

        halconProvider.HObject2Bpp24(ho_ImageReduced, out clipPic);
        ho_Image.Dispose();
    ho_P1r.Dispose();
    ho_ImageReduced.Dispose();  //扣边后的图


  }




}


